### ISSUE TITLE
Bing is open in Demo

### ISSUE THREAD

**Issue by cyber-murmel** [pd4d10/chrome-ui#3]
When I open the [Demo Page](https://pd4d10.github.io/chrome-ui/) (date: 2018-02-01) https://www.bing.com is open in one tab.
Tested on Firefox 58.0 (64-bit).

**Comment by lubiana** [comment]
I have the same issue. Tested in Firefox 58.0.1

**Comment by pd4d10** [comment]
@cyber-murmel Yes, we have https://www.bing.com/ and https://en.wikipedia.org as demo sites of tab#1 and tab#2, since they are popular, and don't have `X-Frame-Options` set so can be loaded in `iframe`.

Could you explain why it is an issue? Thanks!

**Comment by cyber-murmel** [comment]
https://i.imgur.com/fq6VeTN.jpg
